version: '3.8'

services:
  backend:
    build: ./AltitudeIT Full Stack
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyDatabase;User Id=sa;Password=Sifra123!

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Sifra123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
